apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-healing-app
  namespace: self-healing

spec:
  replicas: 3

  selector:
    matchLabels:
      app: self-healing-app

  template:
    metadata:
      labels:
        app: self-healing-app

    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: self-healing-app

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60

        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
          
      containers:
        - name: nginx
          image: self-healing-app:v2
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - NET_BIND_SERVICE
                - SETUID
                - SETGID

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
